//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReportToDoctor
    {
        public int idDoctor { get; set; }
        public string patientsForTomorow { get; set; }
        public string adressesList { get; set; }
        public string machines { get; set; }
        public string fastestWay { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
