//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyRoute
    {
        public System.DateTime dateO { get; set; }
        public int idMishmeret { get; set; }
        public int idDoctor { get; set; }
        public int nunbersOfPatients { get; set; }
        public string currentIndex { get; set; }
    
        public virtual ScheduleForDoctor ScheduleForDoctor { get; set; }
    }
}
