//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.OrderHomeHospitalization = new HashSet<OrderHomeHospitalization>();
            this.ScheduleForDoctor = new HashSet<ScheduleForDoctor>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int codeStatusCovid { get; set; }
        public string gender { get; set; }
        public string hoursOfWork { get; set; }
        public int location { get; set; }
    
        public virtual DailyReportToDoctor DailyReportToDoctor { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual StatusCovid19 StatusCovid19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHomeHospitalization> OrderHomeHospitalization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleForDoctor> ScheduleForDoctor { get; set; }
    }
}
