//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class OritProjectGoodLuckEntities2 : DbContext
    {
        //public OritProjectGoodLuckEntities2()
        //    : base("name=OritProjectGoodLuckEntities2")
        //{
        //}

        protected static OritProjectGoodLuckEntities2 instance;
        public static OritProjectGoodLuckEntities2 Instance()
        {
            lock (typeof(OritProjectGoodLuckEntities2))
            {
                if (instance == null)
                    instance = new OritProjectGoodLuckEntities2();
            }
            return instance;
        }
        protected OritProjectGoodLuckEntities2()
            : base("name=OritProjectGoodLuckEntities2")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<ConditationMedical> ConditationMedical { get; set; }
        public virtual DbSet<DailyReportToDoctor> DailyReportToDoctor { get; set; }
        public virtual DbSet<DailyRoute> DailyRoute { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentOfPatient> EquipmentOfPatient { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<OrderHomeHospitalization> OrderHomeHospitalization { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<ScheduleForDoctor> ScheduleForDoctor { get; set; }
        public virtual DbSet<StatusCovid19> StatusCovid19 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
    }
}
