//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHomeHospitalization
    {
        public int idOrder { get; set; }
        public int idPatient { get; set; }
        public Nullable<int> idDoctor { get; set; }
        public System.DateTime dateOf { get; set; }
        public Nullable<System.DateTime> hourOfVisit { get; set; }
        public Nullable<int> levelOfUrgent { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
