//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.OrderHomeHospitalization = new HashSet<OrderHomeHospitalization>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int statuscovid19 { get; set; }
        public string gender { get; set; }
        public int codeAdress { get; set; }
        public Nullable<int> machine { get; set; }
        public int medicalCondition { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> levelUrgent { get; set; }
        public Nullable<int> doctorId { get; set; }
        public int locationId { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual ConditationMedical ConditationMedical { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual EquipmentOfPatient EquipmentOfPatient { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHomeHospitalization> OrderHomeHospitalization { get; set; }
        public virtual StatusCovid19 StatusCovid191 { get; set; }
    }
}
