//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleForDoctor
    {
        public int idDoctor { get; set; }
        public int idMishmeret { get; set; }
        public string day { get; set; }
        public System.DateTime fromHour { get; set; }
        public System.DateTime toHour { get; set; }
    
        public virtual DailyRoute DailyRoute { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
